#!/bin/bash
sbatch <<EOT
#!/bin/bash
#SBATCH --output=output_$1_$2_$3.txt
#SBATCH --job-name=jsp_$1
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task 4
#SBATCH --mem-per-cpu=16000
#SBATCH --gres=gpu:1
#SBATCH -p gpu -n1
#SBATCH -q gpu-single
hostname
srun --unbuffered python jsp.py -j $1 -m $2 -t $3
exit 0
EOT